Started at: 
Tue Jan 16 08:43:02 CET 2024
Traceback (most recent call last):
  File "/home/dazzolin/test/2024credal_facts/benchmarks/coloring/credal_ad/0_runner.py", line 11, in <module>
    with open(filename,"r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'qr_inc_len_16_ad.lp'

real	0m1.198s
user	0m0.890s
sys	0m0.187s
Ended at: 
Tue Jan 16 08:43:03 CET 2024
